<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "buechertransport"
 *
 * Auto generated by Extension Builder 2013-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Büchertransportdienst',
	'description' => 'Verwaltung des Büchertransportdienstes',
	'category' => 'plugin',
	'author' => 'Dominic Simm',
	'author_email' => 'dominic.simm@sub.uni-goettingen.de',
	'author_company' => 'SUB Göttingen',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.3',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'nkwlib' => '0.0.32',
			'nkwsubmenu' => '2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>